// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VKR_Visik;

#nullable disable

namespace VKR_Visik.Migrations
{
    [DbContext(typeof(ApplicationDdContext))]
    [Migration("20250119134628_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VKR_Visik.Classes.MessageHistory", b =>
                {
                    b.Property<int>("MH_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MH_id"));

                    b.Property<int?>("MH_answer")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MH_data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MH_placemant")
                        .HasColumnType("int");

                    b.Property<int?>("MH_theme")
                        .HasColumnType("int");

                    b.Property<int?>("MH_who")
                        .HasColumnType("int");

                    b.HasKey("MH_id");

                    b.HasIndex("MH_theme");

                    b.HasIndex("MH_who");

                    b.ToTable("MessageHistory");
                });

            modelBuilder.Entity("VKR_Visik.Classes.Sections", b =>
                {
                    b.Property<int>("sections_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sections_Id"));

                    b.Property<DateTime?>("sections_Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("sections_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sections_Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("VKR_Visik.Classes.Themes", b =>
                {
                    b.Property<int>("themes_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("themes_id"));

                    b.Property<int?>("sectionsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("themes_data")
                        .HasColumnType("datetime2");

                    b.Property<string>("themes_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("themes_id");

                    b.HasIndex("sectionsId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("VKR_Visik.Classes.Users", b =>
                {
                    b.Property<int>("users_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("users_id"));

                    b.Property<string>("password_u")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("users_FIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ussers_role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("users_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VKR_Visik.Classes.MessageHistory", b =>
                {
                    b.HasOne("VKR_Visik.Classes.Themes", "Themes")
                        .WithMany()
                        .HasForeignKey("MH_theme");

                    b.HasOne("VKR_Visik.Classes.Users", "Users")
                        .WithMany()
                        .HasForeignKey("MH_who");

                    b.Navigation("Themes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("VKR_Visik.Classes.Themes", b =>
                {
                    b.HasOne("VKR_Visik.Classes.Sections", "Sections")
                        .WithMany()
                        .HasForeignKey("sectionsId");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
